# _config.yml

# Server Config

safe: true

source: ./src
destination: ./_site
relative_permalinks: false

timezone: Europe/London

future: false
lsi: false
highlighter: null
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Coventry Sports Awards 2014

url: http://www.coventrysportsawards.co.uk/2014
static: http://www.coventrysportsawards.co.uk/2014/static
media: http://www.coventrysportsawards.co.uk/2014/media
api: http://www.coventrysportsawards.co.uk/2014/api

## Analytics

google_analytics_id: UA-37915390-6

## Meta

meta:
  author: Coventry Telegraph
  publisher: https://plus.google.com/103544945089638905382
  description:
  keywords:
    - "coventry sports awards"
    - "coventry sport"
    - "sports awards"
    - "sports advertising"
    - "sports awards 2014"
    - "coventry"
    - "coventry sports awards winner"
    - "how to nominate"
    - "coventry telegraph"
    - "coventry times"
    - "sponsor awards"
    - "increase publicity"
  google: https://plus.google.com/103544945089638905382
  twitter:
  facebook:
